# Base Docker Compose File. We assume usage of redis by most (all) APIs due to usage of OAuth by all services
# We also assume MySQL usage in our code.
version: '2'
services:
  redis:
    container_name: hera_be_redis
    image: redis
    ports:
      - "6379"
    networks:
      - main_network
  database:
    container_name: hera_be_mysql
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      MYSQL_USER: "hera_be"
      MYSQL_PASSWORD: "hera_be"
      MYSQL_DATABASE: "hera_be"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - main_network
networks:
  main_network:
    driver: bridge


