apiVersion: apps/v1
kind: Deployment
metadata:
  name: hera_be
  labels:
    app: hera_be
spec:
  selector:
    matchLabels:
      app: hera_be
  template:
    metadata:
      labels:
        app: hera_be
    spec:
      containers:
        - image: acrkongastage.azurecr.io/hera_be:latest
          name: hera_be
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          # Applications
          env:
            - name: NODE_PATH
              value: .
            - name: NODE_ENV
              value: staging
            - name: PORT
              value: "80"
            - name: APP_PORT
              value: "80"
            - name: APP_NAME
              value: hera_be
            - name: ENV
              value: staging

              # Redis
            - name: REDIS_HOST
              value: "hera_be-redis.default.svc.cluster.local."
            - name: REDIS_PORT
              value: "6379"

            # Logging
            - name: LOGGING_LEVEL
              value: debug
            - name: LOGGING_CONSOLE
              value: "true"

            # Database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hera_be-secret
                  key: database-username
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: hera_be-secret
                  key: database-host
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hera_be-secret
                  key: database-password
            - name: DATABASE_NAME
              value: hera_be
            - name: DATABASE_POOL_MAX
              value: "10"
            - name: DATABASE_POOL_MIN
              value: "2"
