apiVersion: apps/v1
kind: Deployment
metadata:
  name: hera-be
  labels:
    app: hera-be
spec:
  selector:
    matchLabels:
      app: hera-be
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: hera-be
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: backend
      containers:
        - image: acrkongaproduction.azurecr.io/hera-be:latest
          name: hera-be
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
          # Applications
          env:
            - name: NODE_PATH
              value: .
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "80"
            - name: WEB_PORT
              value: "80"
            - name: APP_PORT
              value: "80"
            - name: APP_NAME
              value: hera-be
            - name: ENV
              value: production
              # Redis
            - name: REDIS_HOST
              value: "hera-be-redis.default.svc.cluster.local."
            - name: REDIS_PORT
              value: "6379"
            - name: SALT_WORK_FACTOR
              value: "10"

            # Logging
            - name: LOGGING_LEVEL
              value: debug
            - name: LOGGING_CONSOLE
              value: "true"

            # Database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hera-be-secret
                  key: database-username
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: hera-be-secret
                  key: database-host
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hera-be-secret
                  key: database-password
            - name: DATABASE_NAME
              value: hera_db
            - name: DATABASE_POOL_MAX
              value: "10"
            - name: DATABASE_POOL_MIN
              value: "2"

              #JWT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hera-be-secret
                  key: jwt-secret
            - name: JWT_EXPIRY
              value: "1h"

            #BASEURL
            - name: BASE_URL
              value: "https://aff.konga.com"

            #SOCIAL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: hera-be-secret
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hera-be-secret
                  key: google-client-secret

            #OAUTH
            - name: OAUTH_URL
              value: "http://auth.default.svc.cluster.local/v2/"
            - name: OAUTH_CLIENT_ID
              value: hera
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hera-be-secret
                  key: oauth-client-secret
            - name: OAUTH_REQUEST_TIMEOUT
              value: "150000"
            - name: OAUTH_RETRY_COUNT
              value: "3"
            - name: OAUTH_RETRY_DELAY
              value: "100"

            #HERMES
            - name: HERMES_API_URL
              value: "http://hermesapi.default.svc.cluster.local"
            - name: HERMES_SCOPE
              value: "private/hermes/send-notification"
            - name: CONTACT_US_TEMPLATE_NAME
              value: "hera_contact_us"
            - name: CONTACT_US_RECIPIENT
              value: "affiliates@konga.com"
            - name: CONTACT_US_SENDER
              value: "no-reply@konga.com"
            - name: CONTACT_US_SENDER_ID
              value: "Konga Affiliate"
            - name: CONTACT_US_SUBJECT
              value: "Konga Affiliate - Contact Us"
            - name: FORGOT_PASSWORD_TEMPLATE_NAME
              value: "hera_forgot_password"
            - name: FORGOT_PASSWORD_SENDER
              value: "no-reply@konga.com"
            - name: FORGOT_PASSWORD_SENDER_ID
              value: "Konga Affiliate"
